# Generated by Django 3.2.4 on 2021-06-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(help_text='Primer Nombre del Jugador', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(help_text='Posición del Jugador', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='nacionality',
            field=models.CharField(help_text='Nacionalidad del Jugador', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(help_text='Posición del Jugador', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Equipo en el que juega el jugador', on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_player', to='fifa_api.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(help_text='Liga en la que juega el equipo', max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Nombre del equipo', max_length=150),
        ),
    ]
