# Generated by Django 3.2.4 on 2021-06-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_api', '0002_auto_20210619_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('already_integrated', models.BooleanField(default=False)),
                ('start_integration', models.DateTimeField()),
                ('finish_integration', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Integración con el Servicio FIFA',
                'verbose_name_plural': 'Integración con el Servicio FIFA',
                'db_table': 'integration_services',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='page_saved',
            field=models.CharField(default=1, help_text='Pagina en la que se encuentra en la API', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='page_saved',
            field=models.CharField(default=1, help_text='Pagina en la que se encuentra en la API', max_length=5),
            preserve_default=False,
        ),
    ]
