# Generated by Django 3.2.4 on 2021-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa_api', '0003_auto_20210620_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationservices',
            name='num_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='integrationservices',
            name='num_teams',
            field=models.IntegerField(null=True),
        ),
    ]
